export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/users/login',
  },
  USERS: {
    BASE: '/users',
    STAFF: '/users/staff',
    WORKERS: '/users/workers',
    REGISTER: '/users/register',
    byId: (id) => `/users/${id}`,
  },
  CLIENTS: {
    BASE: '/clients',
    REGISTER: '/clients/register',
    byId: (id) => `/clients/${id}`,
    history: (id) => `/clients/${id}/history`,
  },
  PROJECTS: {
    BASE: '/projects',
    MY_PROJECTS: '/projects/my-projects',
    WORKER_PROJECTS: '/projects/worker/projects',
    byId: (id) => `/projects/${id}`,
    progress: (id) => `/projects/${id}/progress`,
    workerTasks: (id) => `/projects/${id}/worker/tasks`,
  },
  TASKS: {
    BASE: '/tasks',
    ALL: '/tasks/all',
    DETAILED: '/tasks/all/detailed',
    WITH_PROJECT_DETAILS: '/tasks/with-project-details',
    STATS: '/tasks/admin/stats',
    DATE_RANGE: '/tasks/admin/date-range',
    BULK_UPDATE: '/tasks/admin/bulk-update-status',
    BULK_ASSIGN: '/tasks/admin/bulk-assign',
    byId: (id) => `/tasks/${id}`,
    status: (id) => `/tasks/${id}/status`,
    detailed: (id) => `/tasks/detailed/${id}`,
    byProject: (id) => `/tasks/project/${id}`,
    byWorker: (id) => `/tasks/worker/${id}`,
    byStatus: (status) => `/tasks/status/${status}`,
    workerPerformance: (id) => `/tasks/admin/worker-performance/${id}`,
  },
  FAQS: {
    BASE: '/faqs',
    ALL: '/faqs/all',
    SEARCH: (term) => `/faqs/search/${term}`,
    byId: (id) => `/faqs/${id}`,
  },
  FILES: {
    byProject: (id) => `/files/project/${id}`,
    download: (id) => `/files/download/${id}`,
    byId: (id) => `/files/${id}`,
  },
};
