export const UI = {
  APP_NAME: 'CIMA CRM',
  LOADING: 'Cargando...',
  LOADING_PANEL: 'Cargando panel...',
  UNAUTHORIZED: 'Acceso no autorizado',

  BUTTONS: {
    CREATE: 'Crear',
    EDIT: 'Editar',
    DELETE: 'Eliminar',
    SAVE: 'Guardar',
    CANCEL: 'Cancelar',
    CLOSE: 'Cerrar',
    SEARCH: 'Buscar',
    RESET: 'Reiniciar',
    APPLY: 'Aplicar',
    EXPORT: 'Exportar',
    RETRY: 'Reintentar',
    LOGIN: 'Iniciar sesión',
    LOGGING_IN: 'Iniciando sesión...',
    LOGOUT: 'Cerrar Sesión',
    BACK: 'Volver al Panel',
    VIEW_DETAILS: 'Ver detalles',
    VIEW_TASKS: 'Ver Tareas',
    UPDATE_STATUS: 'Actualizar Estado',
    NEW_PROJECT: 'Nuevo Proyecto',
    CREATE_CLIENT: 'Crear Cliente',
    CREATE_USER: 'Crear Usuario',
  },

  LABELS: {
    NAME: 'Nombre',
    EMAIL: 'Email',
    PASSWORD: 'Contraseña',
    ADDRESS: 'Dirección',
    PHONE: 'Teléfono',
    PLAN: 'Plan',
    ROLE: 'Rol',
    STATUS: 'Estado',
    DESCRIPTION: 'Descripción',
    PROJECT: 'Proyecto',
    WORKER: 'Trabajador',
    ACTION: 'Acción',
    NEW_STATUS: 'Nuevo Estado',
    CREATED_AT: 'Fecha de creación',
    UPDATED_AT: 'Última actualización',
    ACTIONS: 'Acciones',
    CURRENT_ROLE: 'Rol Actual',
    CHANGE_ROLE: 'Cambiar Rol',
    FILE: 'Archivo',
    ADDITIONAL_INFO: 'Información Adicional',
    SELECT_CLIENT: 'Seleccionar Cliente',
    PROJECT_NAME: 'Nombre del Proyecto',
    QUESTION: 'Pregunta',
    ANSWER: 'Respuesta',
  },

  PLACEHOLDERS: {
    SEARCH_PROJECTS: 'Buscar proyectos...',
    SEARCH_CLIENTS: 'Buscar cliente...',
    SEARCH_USERS: 'Buscar usuario...',
    SEARCH_TASKS: 'Buscar por descripción o nombre de proyecto...',
    SEARCH_FAQS: 'Buscar preguntas frecuentes...',
    EMAIL: 'Correo',
    PASSWORD: 'Contraseña',
    PROJECT_DESCRIPTION: 'Describe los detalles del proyecto...',
    FAQ_QUESTION: 'Escribe la pregunta aquí...',
    FAQ_ANSWER: 'Escribe la respuesta detallada aquí...',
  },

  TABLE: {
    NO_DATA: 'No se encontraron registros',
    NO_PROJECTS: 'No tienes proyectos',
    NO_TASKS: 'No tienes tareas',
    NO_FAQS: 'No hay preguntas frecuentes',
    NO_USERS: 'No se encontraron usuarios',
    SHOWING: 'Mostrando',
    OF: 'de',
  },

  NAVIGATION: {
    HOME: 'Inicio',
    DOCUMENTS: 'Documentos',
    PROJECT_STATUS: 'Estado del Proyecto',
    SUPPORT: 'Soporte',
    MANAGE_FAQS: 'Gestionar FAQs',
    PROJECTS: 'Proyectos',
    MY_PROJECTS: 'Mis Proyectos',
    CUSTOMER_SUPPORT: 'Soporte al Cliente',
    FAQ: 'Preguntas Frecuentes',
  },

  ADMIN_CARDS: {
    PROJECTS: 'Gestión De Proyectos',
    CLIENTS: 'Gestionar Clientes',
    TASKS: 'Gestionar Tareas',
  },
};
